// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arjfwdpajkpwygrnmbse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyamZ3ZHBhamtwd3lncm5tYnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTg2NDMsImV4cCI6MjA3MDI5NDY0M30.FbhBpnIhc7eYQbmf5QT0cqDdCgMg7p0eaUeJxxGbd8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});